// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.stream2000.railgunmq.core;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Empty = 0;</code>
     */
    Empty(0),
    /**
     * <code>PubMessageRequestType = 1;</code>
     */
    PubMessageRequestType(1),
    /**
     * <code>PunMessageResponseType = 2;</code>
     */
    PunMessageResponseType(2),
    /**
     * <code>CreateChannelRequestType = 3;</code>
     */
    CreateChannelRequestType(3),
    /**
     * <code>CreateChannelResponseType = 4;</code>
     */
    CreateChannelResponseType(4),
    /**
     * <code>NodeHeartBeatType = 5;</code>
     */
    NodeHeartBeatType(5),
    /**
     * <code>CSHeartBeatType = 6;</code>
     */
    CSHeartBeatType(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Empty = 0;</code>
     */
    public static final int Empty_VALUE = 0;
    /**
     * <code>PubMessageRequestType = 1;</code>
     */
    public static final int PubMessageRequestType_VALUE = 1;
    /**
     * <code>PunMessageResponseType = 2;</code>
     */
    public static final int PunMessageResponseType_VALUE = 2;
    /**
     * <code>CreateChannelRequestType = 3;</code>
     */
    public static final int CreateChannelRequestType_VALUE = 3;
    /**
     * <code>CreateChannelResponseType = 4;</code>
     */
    public static final int CreateChannelResponseType_VALUE = 4;
    /**
     * <code>NodeHeartBeatType = 5;</code>
     */
    public static final int NodeHeartBeatType_VALUE = 5;
    /**
     * <code>CSHeartBeatType = 6;</code>
     */
    public static final int CSHeartBeatType_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return Empty;
        case 1: return PubMessageRequestType;
        case 2: return PunMessageResponseType;
        case 3: return CreateChannelRequestType;
        case 4: return CreateChannelResponseType;
        case 5: return NodeHeartBeatType;
        case 6: return CSHeartBeatType;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.stream2000.railgunmq.core.Message.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }

  /**
   * Protobuf enum {@code ErrorType}
   */
  public enum ErrorType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>InternalServerError = 1;</code>
     */
    InternalServerError(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>InternalServerError = 1;</code>
     */
    public static final int InternalServerError_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorType forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return InternalServerError;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorType>() {
            public ErrorType findValueByNumber(int number) {
              return ErrorType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.stream2000.railgunmq.core.Message.getDescriptor().getEnumTypes().get(1);
    }

    private static final ErrorType[] VALUES = values();

    public static ErrorType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ErrorType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto*\270\001\n\013MessageType\022\t\n\005Empty" +
      "\020\000\022\031\n\025PubMessageRequestType\020\001\022\032\n\026PunMess" +
      "ageResponseType\020\002\022\034\n\030CreateChannelReques" +
      "tType\020\003\022\035\n\031CreateChannelResponseType\020\004\022\025" +
      "\n\021NodeHeartBeatType\020\005\022\023\n\017CSHeartBeatType" +
      "\020\006*,\n\tErrorType\022\006\n\002OK\020\000\022\027\n\023InternalServe" +
      "rError\020\001B\'\n\034cn.stream2000.railgunmq.core" +
      "B\007Messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
